/* Generated by tools/gen-stage-types.py from ghidra/names/shcpep/ (enums.tsv, types.h): do not edit */
#ifndef STAGE_TYPES_H
#define STAGE_TYPES_H

typedef unsigned char psd_op;
enum {
    OP_DUMMY = 0x00,
    OP_NON_01 = 0x01,
    OP_NON_02 = 0x02,
    OP_NON_03 = 0x03,
    OP_NON_04 = 0x04,
    OP_NON_05 = 0x05,
    OP_EXPORT = 0x06,
    OP_INPORT = 0x07,
    OP_DC = 0x08,
    OP_DZ = 0x09,
    OP_DS = 0x0a,
    OP_DSTR = 0x0b,
    OP_PROGRAM = 0x0c,
    OP_CONST = 0x0d,
    OP_DATA = 0x0e,
    OP_BSS = 0x0f,
    OP_NON_10 = 0x10,
    OP_CASEJMP = 0x11,
    OP_NON_12 = 0x12,
    OP_NON_13 = 0x13,
    OP_CTBL = 0x14,
    OP_CENT = 0x15,
    OP_BBGN = 0x16,
    OP_BEND = 0x17,
    OP_LABEL = 0x18,
    OP_CLABEL = 0x19,
    OP_DLABEL = 0x1a,
    OP_FLABEL = 0x1b,
    OP_NON_1C = 0x1c,
    OP_LINE = 0x1d,
    OP_SWBGN = 0x1e,
    OP_SWEND = 0x1f,
    OP_ENTER = 0x20,
    OP_EXIT = 0x21,
    OP_RETURN = 0x22,
    OP_CALL = 0x23,
    OP_JUMP = 0x24,
    OP_JUMPT = 0x25,
    OP_JUMPF = 0x26,
    OP_MOV_LOC = 0x27,
    OP_MOVA_LC = 0x28,
    OP_MOVA_PC = 0x29,
    OP_MOVI = 0x2a,
    OP_MOVA_FC = 0x2b,
    OP_NON_2C = 0x2c,
    OP_NON_2D = 0x2d,
    OP_NON_2E = 0x2e,
    OP_NON_2F = 0x2f,
    OP_NON_30 = 0x30,
    OP_NON_31 = 0x31,
    OP_NON_32 = 0x32,
    OP_NON_33 = 0x33,
    OP_NON_34 = 0x34,
    OP_NON_35 = 0x35,
    OP_NON_36 = 0x36,
    OP_NON_37 = 0x37,
    OP_NON_38 = 0x38,
    OP_NON_39 = 0x39,
    OP_NON_3A = 0x3a,
    OP_NON_3B = 0x3b,
    OP_NON_3C = 0x3c,
    OP_NON_3D = 0x3d,
    OP_NON_3E = 0x3e,
    OP_NON_3F = 0x3f,
    OP_MOV = 0x40,
    OP_NON_41 = 0x41,
    OP_MOVT = 0x42,
    OP_NON_43 = 0x43,
    OP_MOVA = 0x44,
    OP_NON_45 = 0x45,
    OP_SWAP = 0x46,
    OP_XTRCT = 0x47,
    OP_SHAD = 0x48,
    OP_SHAL = 0x49,
    OP_SHLL = 0x4a,
    OP_SHLL2 = 0x4b,
    OP_SHLL8 = 0x4c,
    OP_SHLL16 = 0x4d,
    OP_ROTL = 0x4e,
    OP_ROTCL = 0x4f,
    OP_CMP_EQ = 0x50,
    OP_CMP_HS = 0x51,
    OP_CMP_GE = 0x52,
    OP_CMP_HI = 0x53,
    OP_CMP_GT = 0x54,
    OP_CMP_PZ = 0x55,
    OP_CMP_PL = 0x56,
    OP_CMP_STR = 0x57,
    OP_SHLD = 0x58,
    OP_SHAR = 0x59,
    OP_SHLR = 0x5a,
    OP_SHLR2 = 0x5b,
    OP_SHLR8 = 0x5c,
    OP_SHLR16 = 0x5d,
    OP_ROTR = 0x5e,
    OP_ROTCR = 0x5f,
    OP_ADD = 0x60,
    OP_ADDC = 0x61,
    OP_ADDV = 0x62,
    OP_SUB = 0x63,
    OP_SUBC = 0x64,
    OP_SUBV = 0x65,
    OP_NON_66 = 0x66,
    OP_NON_67 = 0x67,
    OP_NON_68 = 0x68,
    OP_NON_69 = 0x69,
    OP_NON_6A = 0x6a,
    OP_NON_6B = 0x6b,
    OP_NON_6C = 0x6c,
    OP_NON_6D = 0x6d,
    OP_NON_6E = 0x6e,
    OP_MUL = 0x6f,
    OP_MULS = 0x70,
    OP_MULU = 0x71,
    OP_MAC = 0x72,
    OP_NON_73 = 0x73,
    OP_DIV1 = 0x74,
    OP_DIVOS = 0x75,
    OP_DIVOU = 0x76,
    OP_NON_77 = 0x77,
    OP_NEG = 0x78,
    OP_NEGC = 0x79,
    OP_NON_7A = 0x7a,
    OP_EXTS = 0x7b,
    OP_EXTU = 0x7c,
    OP_NON_7D = 0x7d,
    OP_NON_7E = 0x7e,
    OP_NON_7F = 0x7f,
    OP_AND = 0x80,
    OP_OR = 0x81,
    OP_XOR = 0x82,
    OP_NOT = 0x83,
    OP_NON_84 = 0x84,
    OP_TST = 0x85,
    OP_TAS = 0x86,
    OP_NON_87 = 0x87,
    OP_NOP = 0x88,
    OP_NON_89 = 0x89,
    OP_DT = 0x8a,
    OP_CLRT = 0x8b,
    OP_LDC = 0x8c,
    OP_LDS = 0x8d,
    OP_RTE = 0x8e,
    OP_SETT = 0x8f,
    OP_BF = 0x90,
    OP_BT = 0x91,
    OP_BRA = 0x92,
    OP_BSR = 0x93,
    OP_JMP = 0x94,
    OP_JSR = 0x95,
    OP_RTS = 0x96,
    OP_BT_S = 0x97,
    OP_BF_S = 0x98,
    OP_BSRF = 0x99,
    OP_BRAF = 0x9a,
    OP_CLRMAC = 0x9b,
    OP_STC = 0x9c,
    OP_STS = 0x9d,
    OP_TRAPA = 0x9e,
    OP_SLEEP = 0x9f,
    OP_NON_A0 = 0xa0,
    OP_NON_A1 = 0xa1,
    OP_NON_A2 = 0xa2,
    OP_NON_A3 = 0xa3,
    OP_NON_A4 = 0xa4,
    OP_NON_A5 = 0xa5,
    OP_NON_A6 = 0xa6,
    OP_NON_A7 = 0xa7,
    OP_NON_A8 = 0xa8,
    OP_NON_A9 = 0xa9,
    OP_NON_AA = 0xaa,
    OP_NON_AB = 0xab,
    OP_NON_AC = 0xac,
    OP_NON_AD = 0xad,
    OP_NON_AE = 0xae,
    OP_NON_AF = 0xaf,
    OP_NON_B0 = 0xb0,
    OP_NON_B1 = 0xb1,
    OP_NON_B2 = 0xb2,
    OP_NON_B3 = 0xb3,
    OP_NON_B4 = 0xb4,
    OP_NON_B5 = 0xb5,
    OP_NON_B6 = 0xb6,
    OP_NON_B7 = 0xb7,
    OP_NON_B8 = 0xb8,
    OP_NON_B9 = 0xb9,
    OP_NON_BA = 0xba,
    OP_NON_BB = 0xbb,
    OP_NON_BC = 0xbc,
    OP_NON_BD = 0xbd,
    OP_NON_BE = 0xbe,
    OP_NON_BF = 0xbf,
    OP_NON_C0 = 0xc0,
    OP_NON_C1 = 0xc1,
    OP_NON_C2 = 0xc2,
    OP_NON_C3 = 0xc3,
    OP_NON_C4 = 0xc4,
    OP_NON_C5 = 0xc5,
    OP_NON_C6 = 0xc6,
    OP_NON_C7 = 0xc7,
    OP_NON_C8 = 0xc8,
    OP_NON_C9 = 0xc9,
    OP_NON_CA = 0xca,
    OP_NON_CB = 0xcb,
    OP_NON_CC = 0xcc,
    OP_NON_CD = 0xcd,
    OP_NON_CE = 0xce,
    OP_NON_CF = 0xcf,
    OP_NON_D0 = 0xd0,
    OP_NON_D1 = 0xd1,
    OP_NON_D2 = 0xd2,
    OP_NON_D3 = 0xd3,
    OP_NON_D4 = 0xd4,
    OP_NON_D5 = 0xd5,
    OP_NON_D6 = 0xd6,
    OP_NON_D7 = 0xd7,
    OP_NON_D8 = 0xd8,
    OP_NON_D9 = 0xd9,
    OP_NON_DA = 0xda,
    OP_NON_DB = 0xdb,
    OP_NON_DC = 0xdc,
    OP_NON_DD = 0xdd,
    OP_NON_DE = 0xde,
    OP_NON_DF = 0xdf,
    OP_NON_E0 = 0xe0,
    OP_NON_E1 = 0xe1,
    OP_NON_E2 = 0xe2,
    OP_NON_E3 = 0xe3,
    OP_NON_E4 = 0xe4,
    OP_NON_E5 = 0xe5,
    OP_NON_E6 = 0xe6,
    OP_NON_E7 = 0xe7,
    OP_NON_E8 = 0xe8,
    OP_NON_E9 = 0xe9,
    OP_NON_EA = 0xea,
    OP_NON_EB = 0xeb,
    OP_NON_EC = 0xec,
    OP_NON_ED = 0xed,
    OP_NON_EE = 0xee,
    OP_NON_EF = 0xef,
    OP_NON_F0 = 0xf0,
    OP_NON_F1 = 0xf1,
    OP_NON_F2 = 0xf2,
    OP_NON_F3 = 0xf3,
    OP_NON_F4 = 0xf4,
    OP_NON_F5 = 0xf5,
    OP_NON_F6 = 0xf6,
    OP_NON_F7 = 0xf7,
    OP_NON_F8 = 0xf8,
    OP_NON_F9 = 0xf9,
    OP_NON_FA = 0xfa,
    OP_NON_FB = 0xfb,
    OP_NON_FC = 0xfc,
    OP_NON_FD = 0xfd,
    OP_NON_FE = 0xfe,
    OP_NON_FF = 0xff,
};

typedef struct ea ea;
typedef struct label_ref label_ref;
typedef struct psd psd;
typedef struct code_node code_node;
typedef struct flow_edge flow_edge;
typedef struct flow_block flow_block;
typedef struct symbol symbol;
typedef struct label_block_ref label_block_ref;
typedef struct aux_reg_range aux_reg_range;
typedef struct aux_record aux_record;
typedef struct alloc_chunk alloc_chunk;
typedef struct alloc_size_class alloc_size_class;
typedef struct alloc_class_table alloc_class_table;
typedef struct literal_entry literal_entry;
typedef struct literal_table literal_table;
typedef struct request request;
typedef struct request_section request_section;
typedef struct request_string request_string;
typedef struct request_string12 request_string12;
typedef struct request_sized_string request_sized_string;
typedef struct request_source_file request_source_file;
typedef struct request_entry request_entry;
typedef struct request_cpp_block request_cpp_block;
typedef struct temp_file temp_file;

/* shcpep's records, applied to the Ghidra project by ApplyStageTables.java and compiled into the C rebuild as
   include/stage_types.h (tools/gen-stage-types.py adds a typedef for each struct and the enum constants).
   The names in [brackets] are the stage's own, from its debug dumps (dump_node_list_debug and friends print
   "psdtbl->psdop", "eabase", "labtbl->labno1", ...). Every field sits at its natural alignment, so the layout is
   the same under Ghidra's packing and Visual C++'s. */

/* an operand [eatbl]: the effective address of a psd record's source or destination */
struct ea {
    unsigned char type;          /* +00 [eatype] low 5 bits: EANON 0, EAREGD 1 (Rn), EAIDREG 2 (@Rn), EAPRDEC 3 (@-Rn),
                                    EAPOINC 4 (@Rn+), EACREGD 5 (control reg), EASREGD 6 (system reg), EAIMM 7 (#imm),
                                    EADISP 8 (@(disp,Rn)), EAINDEX 9 (@(R0,Rn)), EAIDPC 10 (@(disp,PC)),
                                    EADSPGBR 11 (@(disp,GBR)), EAIDXGBR 12 (@(R0,GBR)), EAABS 13 */
    char base;                   /* +01 [eabase] base register (0x0f = r15 the stack pointer, 0x6c = the frame) */
    char index;                  /* +02 [eaindex] index register */
    char misc;                   /* +03 [eamisc] */
    int disp;                    /* +04 [eadisp] displacement or immediate value */
    struct label_ref *labels;    /* +08 the labels/symbols the value refers to */
};
// @size ea 0xc

/* a symbol reference of an operand [labtbl], a list */
struct label_ref {
    struct label_ref *next;      /* +00 */
    short labno1;                /* +04 [labno1] label (or symbol) number */
    short labno2;                /* +06 [labno2] second label of a difference (labno1 - labno2), 0 = none */
};
// @size label_ref 0x8

/* a pseudo-code record [psdtbl]: one instruction or directive of the function being compiled */
struct psd {
    psd_op op;                   /* +00 [psdop] */
    char flg;                    /* +01 [psdflg] operand size and other flags */
    char misc;                   /* +02 [psdmisc] */
    char tmp;                    /* +03 [psdtmp] */
    int sptravel;                /* +04 [psdsptravel] stack pointer offset at this record */
    int expno;                   /* +08 [psdexpno] expression number */
    short filno;                 /* +0c [psdfilno] source file */
    unsigned short linno;        /* +0e [psdlinno] source line */
    struct ea *ea1;              /* +10 source operand; a LABEL's [psdlabno] in the low half */
    struct ea *ea2;              /* +14 destination operand */
};
// @size psd 0x18

/* a node of a code block [nodetbl]: up to 15 psd records. The first node of each block links the blocks
   ("Base Next Block"), every node the rest of its block ("Base Next Node") */
struct code_node {
    unsigned char flags;         /* +00 1: the block does not fall through to a label of its own; 2: needs the
                                    after-load clean-up passes again */
    unsigned char psd_count;     /* +01 records used in the block's last node */
    unsigned char unknown_02[2]; /* +02 */
    short labno;                 /* +04 the label the block starts with, 0 = none */
    short target_labno;          /* +06 the label its final branch goes to, 0 = none */
    struct code_node *next_block; /* +08 */
    struct code_node *next;      /* +0c the next node of this block */
    struct psd psd[15];          /* +10 */
};
// @size code_node 0x178

/* one entry of a flow block's predecessor list */
struct flow_edge {
    struct flow_edge *next;      /* +00 */
    struct flow_block *block;    /* +04 */
};
// @size flow_edge 0x8

/* a basic block of the flow graph the final passes (from FUN_00401000) build over the code blocks */
struct flow_block {
    struct code_node *code;      /* +00 the block's first node */
    struct flow_block *next;     /* +04 next in code order */
    struct flow_block *target;   /* +08 the block its final branch goes to */
    struct flow_block *prev;     /* +0c previous in code order */
    struct flow_edge *preds;     /* +10 the blocks that branch here */
    unsigned int live_in[2];     /* +14 registers used before they are set in the block */
    unsigned int defs[2];        /* +1c registers the block sets */
    unsigned char flags;         /* +24 1: ends in an unconditional transfer (RETURN/JUMP/BRA/JMP); 2: EXIT;
                                    4: has a CALL; 8: has an end record (op 0x10); 0x10: only labels so far;
                                    0x20: has a CASEJMP; 0x40: has a volatile operand */
    unsigned char flags2;        /* +25 */
    unsigned char unknown_26[2]; /* +26 */
};
// @size flow_block 0x28

/* a label or other symbol [labtbl entry of the symbol table]: the .asa symbols (load_symbol_aux_record_stream,
   an array of request->label_count) and labels made later (create_symbol_record, blocks of 32), hashed by
   number % 0x3fd into g_symbol_hash */
struct symbol {
    unsigned char type;          /* +00 low 5 bits: the .asa tag 1..0xc (2..5 label kinds whose references are
                                    counted; 0xc function) */
    unsigned char flags;         /* +01 0xc0: high bits of the .asa tag byte; 0x20: referenced */
    unsigned char attr;          /* +02 attribute bits 0..5 from the stream */
    unsigned char attr2;         /* +03 */
    unsigned char unknown_04[2]; /* +04 */
    short number;                /* +06 label/symbol number (the hash key) */
    int value;                   /* +08 */
    char *name;                  /* +0c */
    short aux_index;             /* +10 index into g_aux_record_table (functions) */
    short savelab;               /* +12 [savelab] the label a branch to this one is redirected to (br_brchg) */
    struct symbol *hash_next;    /* +14 next in the hash bucket */
    short header_word;           /* +18 */
    unsigned char unknown_1a[2]; /* +1a */
    int sequence;                /* +1c load order */
    struct label_block_ref *ref_blocks; /* +20 [LISTTBL] the blocks whose final branch goes here */
    int ref_count;               /* +24 reference count (dellab: 0 = dead) */
    struct psd *label_psd;       /* +28 the LABEL record of the label */
};
// @size symbol 0x2c

/* one entry of a symbol's list of referencing blocks [LISTTBL] */
struct label_block_ref {
    struct label_block_ref *next; /* +00 */
    struct code_node *block;      /* +04 0 once unlinked */
};
// @size label_block_ref 0x8

/* a register renaming range of a function (start expno / end expno / before reg / after reg in the
   advance_sua_record_stream debug output) */
struct aux_reg_range {
    struct aux_reg_range *next;  /* +00 */
    char before_reg;             /* +04 */
    char after_reg;              /* +05 */
    unsigned char unknown_06[2]; /* +06 */
    int start_expno;             /* +08 */
    int end_expno;               /* +0c */
};
// @size aux_reg_range 0x10

/* the per-function aux record (.asa tag 0xc), an array of request->aux_count */
struct aux_record {
    int frame_size;              /* +00 local frame */
    short saved_regs;            /* +04 bit n: Rn saved */
    short saved_regs2;           /* +06 bit n: register 0x10+n saved */
    unsigned char saved_sys;     /* +08 bit 0: register 0x67, bit 1: register 0x68 saved */
    unsigned char unknown_09;    /* +09 */
    unsigned short flags;        /* +0a 0x8000: PR not saved (leaf); 0x4000; 0x0800/0x1000/0x1800: the kind of
                                    stack_value; 0x2000: unknown_byte present */
    int max_stack;               /* +0c maximum stack depth */
    int stack_value;             /* +10 */
    unsigned short range_count;  /* +14 */
    unsigned char unknown_byte;  /* +16 */
    unsigned char saved_mac;     /* +17 bit 0: MACL, bit 1: MACH saved */
    struct aux_reg_range *ranges; /* +18 */
    int unknown_1c;              /* +1c */
    int asb_word;                /* +20 written to .asb */
    int sp_adjust;               /* +24 stack adjustment folded in by fold_add_immediates */
    char reg28;                  /* +28 a register number, written to .asb */
    unsigned char unknown_29[3]; /* +29 */
    unsigned char asb_bytes[0x17]; /* +2c copied from the stream to .asb */
    unsigned char unknown_43;    /* +43 */
};
// @size aux_record 0x44

/* the size-class allocator (alloc_zeroed, try_alloc_zeroed, pool_free): a chunk of one size class */
struct alloc_chunk {
    struct alloc_chunk *next;    /* +00 */
    char *cursor;                /* +04 next never-used byte */
    char *end;                   /* +08 end of data */
    void *free_list;             /* +0c freed blocks, linked through their first word */
    int free_count;              /* +10 */
    unsigned char data[0x400];   /* +14 */
};
// @size alloc_chunk 0x414

struct alloc_size_class {
    short size;                  /* +00 block size */
    unsigned char unknown_02[2]; /* +02 */
    struct alloc_chunk *chunks;  /* +04 */
};
// @size alloc_size_class 0x8

/* a block of up to 32 size classes; the list head is g_alloc_size_classes */
struct alloc_class_table {
    short count;                 /* +00 classes used */
    unsigned char unknown_02[2]; /* +02 */
    struct alloc_class_table *next; /* +04 */
    struct alloc_size_class cls[32]; /* +08 */
};
// @size alloc_class_table 0x108

/* a literal of the pool tables (g_word_literal_table, g_long_literal_table, g_frame_offset_literal_table) */
struct literal_entry {
    struct literal_entry *next;  /* +00 insertion order */
    struct literal_entry *hash_next; /* +04 bucket chain */
    int value;                   /* +08 */
    struct label_ref *labels;    /* +0c */
};
// @size literal_entry 0x10

struct literal_table {
    struct literal_entry *head;  /* +000 */
    struct literal_entry *tail;  /* +004 */
    int count;                   /* +008 */
    struct literal_entry *buckets[0x7f]; /* +00c hash = (value + the label numbers) % 0x7f */
};
// @size literal_table 0x208

/* the request record every SHC stage loads from its counted request file (load_request_record_file) and stores
   back: the file's first short is the size of this fixed part, read raw; the pointer fields are then replaced by
   the strings and lists that follow in the file (read_request_variable_part). Fields shcpep does not use are
   unknown_ */
struct request {
    char *source_name;                   /* +000 the source file, for messages */
    unsigned char unknown_004[0x14];     /* +004 */
    short cpu;                           /* +018 nonzero: JUMPT/JUMPF take part in the branch passes */
    short pic;                           /* +01a nonzero: call/jump target literals become label differences */
    unsigned char unknown_01c[8];        /* +01c */
    struct request_section *sections;    /* +024 */
    unsigned char unknown_028[0xe];      /* +028 */
    char macsave;                        /* +036 0: calls clobber MACH/MACL */
    unsigned char unknown_037[1];        /* +037 */
    char *string_038;                    /* +038 */
    char *string_03c;                    /* +03c */
    struct request_string *string_list_040; /* +040 */
    unsigned char unknown_044[4];        /* +044 */
    struct request_string12 *string_list_048; /* +048 */
    struct request_sized_string *sized_string_list_04c; /* +04c */
    char *path_050;                      /* +050 */
    char *path_054;                      /* +054 */
    char *path_058;                      /* +058 */
    char *path_05c;                      /* +05c */
    char *message_path;                  /* +060 the message record file */
    char *path_064;                      /* +064 */
    char *path_068;                      /* +068 */
    char *path_06c;                      /* +06c */
    char *path_070;                      /* +070 */
    char *path_074;                      /* +074 */
    char *path_078;                      /* +078 */
    char *path_07c;                      /* +07c */
    char *path_080;                      /* +080 */
    char *sua_path;                      /* +084 .sua input */
    char *sub_path;                      /* +088 .sub output */
    char *sud_path;                      /* +08c .sud */
    char *path_090;                      /* +090 */
    char *ofb_path;                      /* +094 .ofb output */
    char *asa_path;                      /* +098 .asa input */
    char *asb_path;                      /* +09c .asb output */
    char *path_0a0;                      /* +0a0 */
    char *lit_path;                      /* +0a4 .lit output */
    char *path_0a8;                      /* +0a8 */
    int label_count;                     /* +0ac symbols in the .asa stream; the label counter is stored back */
    unsigned char unknown_0b0[8];        /* +0b0 */
    struct request_entry *entry11_list_0b8; /* +0b8 */
    struct request_entry *entry11_list_0bc; /* +0bc */
    struct request_entry *entry12_list_0c0; /* +0c0 */
    unsigned char unknown_0c4[4];        /* +0c4 */
    int warning_count;                   /* +0c8 */
    int error_count;                     /* +0cc */
    unsigned char unknown_0d0[4];        /* +0d0 */
    int result_0d4;                      /* +0d4 */
    unsigned char unknown_0d8[0x14];     /* +0d8 */
    struct request_source_file *source_files; /* +0ec file number -> name, for messages */
    unsigned char unknown_0f0[0x20];     /* +0f0 */
    int aux_count;                       /* +110 aux (function) records in the .asa stream */
    char *string_114;                    /* +114 */
    int stage;                           /* +118 the stage that loaded it (3 = shcpep) */
    char *compiler_version;              /* +11c */
    char *copyright;                     /* +120 */
    unsigned char message_flags;         /* +124 */
    unsigned char unknown_125[0x13];     /* +125 */
    unsigned int stage_flags;            /* +138 debug-trace flags (g_stage_flags) */
    unsigned char flags_13c;             /* +13c */
    unsigned char flags_13d;             /* +13d */
    unsigned char unknown_13e[2];        /* +13e */
    char *string_140;                    /* +140 */
    struct request_cpp_block *cpp_block; /* +144 nonzero: C++ */
    unsigned char unknown_148[1];        /* +148 */
    char scratch_bank_reg_count;         /* +149 registers 0x14.. and 0x24.. treated as call-clobbered */
    char message_all;                    /* +14a */
    char pool_flag_14b;                  /* +14b */
    unsigned char unknown_14c[4];        /* +14c */
    unsigned int reg_mask_150;           /* +150 one bit per register number */
    unsigned char abs16;                 /* +154 */
    unsigned char unknown_155[7];        /* +155 */
    char *string_15c;                    /* +15c */
    int info_count;                      /* +160 */
};
// @size request 0x164

/* a section record of request->sections */
struct request_section {
    short id;                            /* +00 section number */
    short name_len;                      /* +02 */
    char *name;                          /* +04 */
    int unknown_08;                      /* +08 */
    unsigned char unknown_0c[0xc];       /* +0c */
    int unknown_18;                      /* +18 */
    struct request_section *next;        /* +1c */
};
// @size request_section 0x20

struct request_string {
    struct request_string *next;         /* +00 */
    char *str;                           /* +04 */
};
// @size request_string 0x8

struct request_string12 {
    struct request_string12 *next;       /* +00 */
    char *str;                           /* +04 */
    unsigned char unknown_08[4];         /* +08 */
};
// @size request_string12 0xc

struct request_sized_string {
    struct request_sized_string *next;   /* +00 */
    char *str;                           /* +04 */
    short len;                           /* +08 */
    unsigned char unknown_0a[2];         /* +0a */
};
// @size request_sized_string 0xc

struct request_source_file {
    struct request_source_file *next;    /* +00 */
    short filno;                         /* +04 */
    short name_len;                      /* +06 */
    char *name;                          /* +08 */
};
// @size request_source_file 0xc

/* node of the request's 11- and 12-byte entry lists (16 bytes in memory) */
struct request_entry {
    struct request_entry *next;          /* +00 */
    unsigned char a[4];                  /* +04 */
    unsigned char b[4];                  /* +08 */
    unsigned char c[4];                  /* +0c */
};
// @size request_entry 0x10

struct request_cpp_block {
    unsigned char unknown_00[4];         /* +00 */
    char *strings[5];                    /* +04 */
};
// @size request_cpp_block 0x18

/* a temporary file of g_temp_files (open_temp_file, close_and_delete_temp_files) */
struct temp_file {
    char *path;                  /* +00 */
    FILE *file;                  /* +04 */
};
// @size temp_file 0x8

typedef char _size_check_ea[(sizeof(ea) == 0xc) ? 1 : -1];
typedef char _size_check_label_ref[(sizeof(label_ref) == 0x8) ? 1 : -1];
typedef char _size_check_psd[(sizeof(psd) == 0x18) ? 1 : -1];
typedef char _size_check_code_node[(sizeof(code_node) == 0x178) ? 1 : -1];
typedef char _size_check_flow_edge[(sizeof(flow_edge) == 0x8) ? 1 : -1];
typedef char _size_check_flow_block[(sizeof(flow_block) == 0x28) ? 1 : -1];
typedef char _size_check_symbol[(sizeof(symbol) == 0x2c) ? 1 : -1];
typedef char _size_check_label_block_ref[(sizeof(label_block_ref) == 0x8) ? 1 : -1];
typedef char _size_check_aux_reg_range[(sizeof(aux_reg_range) == 0x10) ? 1 : -1];
typedef char _size_check_aux_record[(sizeof(aux_record) == 0x44) ? 1 : -1];
typedef char _size_check_alloc_chunk[(sizeof(alloc_chunk) == 0x414) ? 1 : -1];
typedef char _size_check_alloc_size_class[(sizeof(alloc_size_class) == 0x8) ? 1 : -1];
typedef char _size_check_alloc_class_table[(sizeof(alloc_class_table) == 0x108) ? 1 : -1];
typedef char _size_check_literal_entry[(sizeof(literal_entry) == 0x10) ? 1 : -1];
typedef char _size_check_literal_table[(sizeof(literal_table) == 0x208) ? 1 : -1];
typedef char _size_check_request[(sizeof(request) == 0x164) ? 1 : -1];
typedef char _size_check_request_section[(sizeof(request_section) == 0x20) ? 1 : -1];
typedef char _size_check_request_string[(sizeof(request_string) == 0x8) ? 1 : -1];
typedef char _size_check_request_string12[(sizeof(request_string12) == 0xc) ? 1 : -1];
typedef char _size_check_request_sized_string[(sizeof(request_sized_string) == 0xc) ? 1 : -1];
typedef char _size_check_request_source_file[(sizeof(request_source_file) == 0xc) ? 1 : -1];
typedef char _size_check_request_entry[(sizeof(request_entry) == 0x10) ? 1 : -1];
typedef char _size_check_request_cpp_block[(sizeof(request_cpp_block) == 0x18) ? 1 : -1];
typedef char _size_check_temp_file[(sizeof(temp_file) == 0x8) ? 1 : -1];

#endif
