#!/usr/bin/env python3
"""Write rebuild/<stage>/src/_stockdata.c from the stage's Release 26 executable.

Usage: python tools/gen-stockdata.py <stage> [<stage> ...] [--exe <path>]

The rebuild keeps the stock program's data (.rdata and .data) as one byte array, g_sd; every data global is a
macro for the lvalue at its stock offset (include/decls.h). The file holds those bytes, the offsets of the words
the stock .reloc table lists, and _stockdata_relocate(), which main() calls first: it turns each listed word's
stock address into the rebuild's (data: g_sd + offset; code: _translate_text_va() of src/_relocs.c).
The bytes are Release 26's, so the file is made from your copy (extracted/bin by default) and not kept in git.
"""
import argparse, struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def sections(d):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    n = struct.unpack_from("<H", d, pe + 6)[0]
    opt = struct.unpack_from("<H", d, pe + 20)[0]
    base = struct.unpack_from("<I", d, pe + 24 + 28)[0]
    secs = []
    for i in range(n):
        name, vs, va, rs, ra = struct.unpack_from("<8sIIII", d, pe + 24 + opt + 40 * i)
        secs.append((name.rstrip(b"\0").decode(), base + va, vs, rs, ra))
    rva, size = struct.unpack_from("<II", d, pe + 24 + 96 + 5 * 8)
    return base, secs, rva, size


def stockdata_source(stage, d):
    base, secs, rrva, rsize = sections(d)
    data = [s for s in secs if s[0] in (".rdata", ".data")]
    lo, hi = min(s[1] for s in data), max(s[1] + s[2] for s in data)
    text = next(s for s in secs if s[0] == ".text")
    blob = bytearray(hi - lo)
    for nm, va, vs, rs, ra in data:
        blob[va - lo:va - lo + min(vs, rs)] = d[ra:ra + min(vs, rs)]
    off = next(ra + rrva - (va - base) for _, va, vs, rs, ra in secs if va - base <= rrva < va - base + vs)
    p, end, sites = off, off + rsize, []
    while p < end:
        page, bs = struct.unpack_from("<II", d, p)
        if bs == 0:
            break
        for k in range((bs - 8) // 2):
            e = struct.unpack_from("<H", d, p + 8 + 2 * k)[0]
            if e >> 12 == 3 and lo <= base + page + (e & 0xFFF) < hi:
                sites.append(base + page + (e & 0xFFF))
        p += bs
    src = [f"/* Generated by tools/gen-stockdata.py: the stock data image {lo:#010x}..{hi:#010x} of {stage}.exe */", "",
           "extern unsigned int _translate_text_va(unsigned int va);", "", f"unsigned char g_sd[{hi - lo:#x}] = {{"]
    for i in range(0, len(blob), 16):
        src.append("    " + ",".join(f"0x{b:02x}" for b in blob[i:i + 16]) + ",")
    src += ["};", "", f"static const unsigned int _sd_sites[{len(sites)}] = {{"]
    for i in range(0, len(sites), 8):
        src.append("    " + ",".join(f"{v - lo:#07x}" for v in sites[i:i + 8]) + ",")
    src += ["};", "", "void _stockdata_relocate(void) {", "    unsigned int i, v, t;",
            f"    for (i = 0; i < {len(sites)}u; i++) {{", "        unsigned int *p = (unsigned int *)(g_sd + _sd_sites[i]);",
            "        v = *p;", f"        if (v >= {lo:#x}u && v <= {hi:#x}u) *p = (unsigned int)g_sd + (v - {lo:#x}u);",
            f"        else if (v >= {text[1]:#x}u && v < {text[1] + text[2]:#x}u) {{",
            "            t = _translate_text_va(v);",
            "            *p = t;   /* 0 for a function not in the rebuild (stock CRT init/term entries) */",
            "        }", "    }", "}"]
    return "\n".join(src) + "\n", lo, hi, len(sites)


def write_stockdata(stage, exe=None):
    exe = Path(exe) if exe else ROOT / "extracted/bin" / f"{stage}.exe"
    text, lo, hi, n = stockdata_source(stage, exe.read_bytes())
    with open(ROOT / "rebuild" / stage / "src/_stockdata.c", "w", newline="\n") as f:
        f.write(text)
    return lo, hi, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", nargs="+"); ap.add_argument("--exe")
    a = ap.parse_args()
    for s in a.stage:
        lo, hi, n = write_stockdata(s, a.exe)
        print(f"{s}: data {lo:#x}..{hi:#x}, {n} pointer sites")


if __name__ == "__main__":
    main()
