#!/usr/bin/env python3
"""Write a C rebuild's include/stage_types.h from the stage's naming tables (ghidra/names/<stage>/), the same
definitions ApplyStageTables.java gives the Ghidra project, so the exported C compiles against them:

  enums.tsv  each enum as a typedef of the integer type of its size (the struct fields keep their width) plus its
             members as enum constants
  types.h    copied as it is, after a typedef for every struct/union it defines (Ghidra prints `psd *`, not
             `struct psd *`); its "// @size NAME 0xNN" lines become compile-time size checks

Usage: python tools/gen-stage-types.py <stage>     (prints the names it defines, one per line, to names.txt beside it)
"""
import re, sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INT = {1: "unsigned char", 2: "unsigned short", 4: "unsigned int"}


def main():
    stage = sys.argv[1]
    T = ROOT / "ghidra/names" / stage
    out_dir = ROOT / "rebuild" / stage / "include"
    enums = OrderedDict()
    if (T / "enums.tsv").exists():
        for l in (T / "enums.tsv").read_text().splitlines():
            if not l.strip() or l.startswith("#"):
                continue
            name, size, member, value = [x.strip() for x in l.split("\t")[:4]]
            enums.setdefault(name, (int(size, 0), []))[1].append((member, value))
    types = (T / "types.h").read_text() if (T / "types.h").exists() else ""
    tags = OrderedDict((m.group(2), m.group(1)) for m in re.finditer(r"^\s*(struct|union)\s+(\w+)\s*\{", types, re.M))
    sizes = re.findall(r"^\s*// @size (\w+) (0x[0-9a-fA-F]+|\d+)", types, re.M)
    o = [f"/* Generated by tools/gen-stage-types.py from ghidra/names/{stage}/ (enums.tsv, types.h): do not edit */",
         "#ifndef STAGE_TYPES_H", "#define STAGE_TYPES_H", ""]
    for name, (size, members) in enums.items():
        o.append(f"typedef {INT[size]} {name};")
        o.append("enum {")
        o += [f"    {m} = {v}," for m, v in members]
        o.append("};")
        o.append("")
    o += [f"typedef {kind} {tag} {tag};" for tag, kind in tags.items()]
    o += ["", types.strip(), ""]
    o += [f"typedef char _size_check_{n}[(sizeof({n}) == {s}) ? 1 : -1];" for n, s in sizes]
    o += ["", "#endif", ""]
    (out_dir / "stage_types.h").write_text("\n".join(o))
    (out_dir / "stage_types.names").write_text("\n".join(list(enums) + list(tags)) + "\n")
    print(f"stage_types.h: {len(enums)} enums, {len(tags)} structs/unions, {len(sizes)} size checks")


if __name__ == "__main__":
    main()
